# See the github page (https://github.com/TruFoox/HoneyWasp) for config help

[General_Settings]
; Your bot's token for logging in to Discord
discord_bot_token = TOKENHERE

; Discord webhook URL for logging or alerts
webhook_url = WEBHOOKHERE

; The service to start automatically (e.g., 'instagram')
autostart = false

; Enables verbose logging and debug output
debug_mode = false


[Instagram_Settings]
; Instagram API key for posting
api_key = KEYHERE

; Instagram user ID for API access
user_id = IDHERE

; Posting mode (Auto or Manual)
; 	Auto = Automatically grab posts off reddit
; 	Manual = Post random image url (eventually will support videos) from media.json
post_mode = auto

; Time in minutes between posts
time_between_posts = 1

; How many failed post attempts before giving up
attempts_before_timeout = 50

; Subreddits to pull content from (seperate by commas, auto post_mode only, NO SPACES, DO NOT INCLUDE r/)
subreddits = memes,meme,comedyheaven

; Blacklisted words in content (case-insensitive, seperate by commas, auto post_mode only, NO SPACES)
blacklist = nigg,fag

; Whether to allow posting the same image twice (auto post_mode only)
duplicates_allowed = false

; Allow NSFW content (FALSE HIGHLY RECOMMENDED - PREVENTS BAN)
nsfw_allowed = false

; Use Reddit post title as the caption
use_reddit_caption = false

; Words that, if found in a caption, will the backup caption to be used instead (seperate by commas, NO SPACES)
caption_blacklist = nigg,fag

; Default caption (used when Reddit caption is blacklisted or in Manual mode)
default_caption = Hi!

; Hashtags to append to each Instagram post
hashtags = #meme #memes #funny #dankmemes #memesdaily #funnymemes #lol #humor #follow #dank #love #like #memepage #comedy #instagram #dankmeme #tiktok #anime #lmao #dailymemes #edgymemes #fun #ol #offensivememes #memestagram #bhfyp #funnymeme #instagood #shitpost #memer
